# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "ARCHS4 Workshop by the Ma'ayan Lab"
description:	       " "
author:              "Heesu Kim"
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml


favicon: favicon.io
url: "https://maayanlab.github.io/"
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/Workshop.io/" # the subpath of your site, e.g. /blog
